In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4],
                [2,1,5,6],
                [3,5,1,7],
                [4,6,7,1]
                            ])
print(arr)


[[1 2 3 4]
 [2 1 5 6]
 [3 5 1 7]
 [4 6 7 1]]


In [5]:
sub_mat_index = np.ix_([1,2,3], [1,2,3])
print("index combination:\n", sub_mat_index)
print("extracted matrix:\n",arr[sub_mat_index])

index combination:
 (array([[1],
       [2],
       [3]]), array([[1, 2, 3]]))
extracted matrix:
 [[1 5 6]
 [5 1 7]
 [6 7 1]]


In [6]:
sub_mat_vec = np.ix_([0], [1,2,3])
print("line vectror:\n", arr[sub_mat_vec])
sub_mat_vec = np.ix_([1,2,3],[0])
print("column vectror:\n", arr[sub_mat_vec])

line vectror:
 [[2 3 4]]
column vectror:
 [[2]
 [3]
 [4]]


In [7]:
sub_mat_index = np.ix_([0,2,3], [0,2,3])
print("index combination:\n", sub_mat_index)
print("extracted matrix:\n",arr[sub_mat_index])
sub_mat_vec = np.ix_([0,2,3],[1])
print("column vectror:\n", arr[sub_mat_vec])

index combination:
 (array([[0],
       [2],
       [3]]), array([[0, 2, 3]]))
extracted matrix:
 [[1 3 4]
 [3 1 7]
 [4 7 1]]
column vectror:
 [[2]
 [5]
 [6]]


In [10]:
sub_mat_index = np.ix_([2,0,3], [2,0,3])
print("index combination:\n", sub_mat_index)
print("extracted matrix:\n",arr[sub_mat_index])
sub_mat_vec = np.ix_([2,0,3],[1])
print("column vectror:\n", arr[sub_mat_vec])


index combination:
 (array([[2],
       [0],
       [3]]), array([[2, 0, 3]]))
extracted matrix:
 [[1 3 7]
 [3 1 4]
 [7 4 1]]
column vectror:
 [[5]
 [2]
 [6]]
