In [1]:
import numpy as np

In [11]:
arr = np.array([[1,2,3,4],
       [5,1,6,7],
       [8,9,1,10],
       [11,12,13,1]
       ])
print(arr)

[[ 1  2  3  4]
 [ 5  1  6  7]
 [ 8  9  1 10]
 [11 12 13  1]]


In [12]:
index = np.ix_([2,3], [2,3])
print(index)
print(arr[index])

(array([[2],
       [3]]), array([[2, 3]]))
[[ 1 10]
 [13  1]]
