In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from dcca import detrended_correlation
from itertools import combinations


import time

In [2]:
series_count = 8

In [3]:
url = 'https://tinyurl.com/zbtestdata64c'



In [4]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 8)

In [5]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
 4   Fc2.    19920 non-null  float64
 5   Fc4.    19920 non-null  float64
 6   Fc6.    19920 non-null  float64
 7   C5..    19920 non-null  float64
dtypes: float64(8)
memory usage: 1.2 MB


In [7]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 ... -8.0e-06 -4.0e-05 -5.4e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 ... -2.4e-05 -5.8e-05 -5.1e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 ... -2.9e-05 -6.6e-05 -6.1e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05 ... -3.0e-06  1.0e-06  2.1e-05]
 [ 3.8e-05  2.7e-05  2.8e-05 ...  1.2e-05  9.0e-06  3.4e-05]
 [ 5.0e-05  3.5e-05  4.1e-05 ...  2.6e-05  2.0e-05  2.6e-05]]


In [ ]:
result_list =[]
start_time = time.time()
dcca_of = combinations(range(len(df.columns)), 2)
for i in dcca_of:
    x = mat[:,i[0]]
    y = mat[:,i[1]]
    print(x.shape)
    temp = []
    for j in tws:
        temp.append( detrended_correlation(x=x, y=y, time_scale=j, time_lag=0) )
    result_list.append(temp)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

(19920,)
(19920,)
(19920,)
(19920,)
(19920,)


In [ ]:
result_list

[[np.float64(0.920127026798953),
  np.float64(0.8210331245806517),
  np.float64(0.7116030039956598),
  np.float64(0.6735328102370122),
  np.float64(0.6179228589454193),
  np.float64(0.9554356701164541),
  np.float64(0.8620291498222451),
  np.float64(0.8232448681477421),
  np.float64(0.7570509167447026),
  np.float64(0.9493497614364492),
  np.float64(0.9136518262839727),
  np.float64(0.8381102479669378),
  np.float64(0.95885945568144),
  np.float64(0.8855638178860612),
  np.float64(0.9570850099663539)],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [ ]:
result_array = np.array(result_list)
result_array

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (42,) + inhomogeneous part.