<a href="https://colab.research.google.com/github/255ribeiro/paper_zebendelib/blob/main/notebooks/test_n_series_opt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install zebende==0.2.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.7/670.7 kB 1.3 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zebende as zb
import time

### Set the number of time series to run the test

In [3]:
series_count = 4

In [4]:
url = 'https://tinyurl.com/zbtestdata64c'

In [5]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 4)

In [6]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
dtypes: float64(4)
memory usage: 622.6 KB


In [8]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 -1.2e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 -1.2e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 -1.9e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05  3.0e-06]
 [ 3.8e-05  2.7e-05  2.8e-05  1.9e-05]
 [ 5.0e-05  3.5e-05  4.1e-05  4.0e-05]]


In [10]:
start_time = time.time()
int_data = zb.integrated_series(mat)
dfa, dcca, pdcca = zb.p_dcca(int_data, tws)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 40.56216549873352 seconds


In [11]:
pdcca

array([[0.93385127, 0.84627662, 0.74370751, 0.96224493, 0.87332455,
        0.95429428],
       [0.93802811, 0.85429926, 0.75425558, 0.96423202, 0.87739089,
        0.95594667],
       [0.94437743, 0.86733248, 0.77324954, 0.96766975, 0.88677884,
        0.95970622],
       [0.9486037 , 0.87586802, 0.78652595, 0.9699226 , 0.89435699,
        0.96292363],
       [0.95125618, 0.88058534, 0.79419589, 0.97114148, 0.89937412,
        0.96534972],
       [0.9528963 , 0.88289279, 0.79836552, 0.97175103, 0.90269281,
        0.96717914],
       [0.9543565 , 0.88427399, 0.80166248, 0.97217315, 0.90605317,
        0.96919218],
       [0.95557301, 0.88521963, 0.80442855, 0.97246123, 0.90893104,
        0.97095957],
       [0.95635328, 0.88620476, 0.80653308, 0.97267585, 0.91048361,
        0.97184485],
       [0.95761715, 0.88853259, 0.8105758 , 0.97314899, 0.91272187,
        0.97289315],
       [0.95879232, 0.89121722, 0.81481988, 0.9736959 , 0.9147311 ,
        0.97363207],
       [0.95979339, 0