<a href="https://colab.research.google.com/github/255ribeiro/paper_zebendelib/blob/main/notebooks/test_n_series_opt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zebende as zb
import time

### Set the number of time series to run the test

In [ ]:
series_count = 4

In [ ]:
url = 'https://tinyurl.com/zbtestdata64c'

In [ ]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

In [ ]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15742 entries, 0 to 15741
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   F3      15742 non-null  float64
 1   F6      15742 non-null  float64
 2   P3      15742 non-null  float64
 3   P6      15742 non-null  float64
dtypes: float64(4)
memory usage: 492.1 KB


In [ ]:
mat = df.to_numpy()
print(mat)

[[-28. -57. -43. -52.]
 [-32. -67. -67. -60.]
 [-44. -74. -74. -66.]
 ...
 [-15. -54. -59. -57.]
 [  0. -41. -25. -47.]
 [-15. -48. -50. -72.]]


In [ ]:
start_time = time.time()
int_data = zb.integrated_series(mat)
dfa, dcca, pdcca = zb.p_dcca(mat, tws)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 27.520853996276855 seconds


In [ ]:
pdcca

array([[0.82382562, 0.60221892, 0.4972079 , 0.47481783, 0.45285253,
        0.7601306 ],
       [0.8293883 , 0.59211517, 0.48657525, 0.46388036, 0.44368493,
        0.74228963],
       [0.84238743, 0.58879398, 0.48116275, 0.46374061, 0.44384958,
        0.72470812],
       [0.85289386, 0.59398261, 0.48538103, 0.47080673, 0.44906472,
        0.72162842],
       [0.86089761, 0.59837119, 0.48988818, 0.47548929, 0.45263663,
        0.72407422],
       [0.8669021 , 0.60265531, 0.49525052, 0.47934242, 0.45664922,
        0.72899719],
       [0.87294803, 0.61189363, 0.50833982, 0.4867668 , 0.4674857 ,
        0.73786364],
       [0.87855621, 0.62416404, 0.52784167, 0.496652  , 0.48462917,
        0.74894607],
       [0.88211647, 0.62978104, 0.53838404, 0.50122718, 0.49382512,
        0.75525081],
       [0.88689752, 0.63414099, 0.55000882, 0.50404329, 0.50287997,
        0.76291818],
       [0.89019391, 0.63751174, 0.55940137, 0.50544241, 0.50960251,
        0.77008399],
       [0.89284691, 0