<a href="https://colab.research.google.com/github/255ribeiro/paper_zebendelib/blob/main/notebooks/test_n_series_opt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
!pip install zebende==0.2.2

### Set the number of time series to run the test

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zebende as zb
import time

In [25]:
series_count = 12

In [26]:
url = 'https://tinyurl.com/zbtestdata64c'

In [27]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape, df.columns.to_numpy()

(19920, 64)


((19920, 12),
 array(['Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..',
        'C3..', 'C1..', 'Cz..', 'C2..'], dtype=object))

In [28]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
 4   Fc2.    19920 non-null  float64
 5   Fc4.    19920 non-null  float64
 6   Fc6.    19920 non-null  float64
 7   C5..    19920 non-null  float64
 8   C3..    19920 non-null  float64
 9   C1..    19920 non-null  float64
 10  Cz..    19920 non-null  float64
 11  C2..    19920 non-null  float64
dtypes: float64(12)
memory usage: 1.8 MB


In [30]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 ... -1.4e-05 -2.9e-05 -1.5e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 ... -2.3e-05 -4.1e-05 -3.1e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 ... -3.6e-05 -5.3e-05 -4.1e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05 ...  2.5e-05  3.3e-05  3.7e-05]
 [ 3.8e-05  2.7e-05  2.8e-05 ...  4.0e-05  5.1e-05  5.5e-05]
 [ 5.0e-05  3.5e-05  4.1e-05 ...  3.8e-05  4.9e-05  5.5e-05]]


In [31]:
start_time = time.time()
int_data = zb.integrated_series(mat, axis=1)
dfa, dcca, pdcca = zb.p_dcca(int_data, tws, axis=1)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 150.1963710784912 seconds


In [32]:
pdcca

array([[0.93385127, 0.84627662, 0.74370751, ..., 0.96825001, 0.89932728,
        0.93776362],
       [0.93802811, 0.85429926, 0.75425558, ..., 0.9697086 , 0.90139431,
        0.94032568],
       [0.94437743, 0.86733248, 0.77324954, ..., 0.9728351 , 0.90693506,
        0.94457491],
       ...,
       [0.93700383, 0.87551046, 0.79527912, ..., 0.94109654, 0.70806739,
        0.64554058],
       [0.93367503, 0.87034236, 0.79027875, ..., 0.93495603, 0.69496998,
        0.624299  ],
       [0.92968033, 0.86377303, 0.78272763, ..., 0.92802758, 0.68128159,
        0.60301603]])