<a href="https://colab.research.google.com/github/255ribeiro/paper_zebendelib/blob/main/notebooks/test_n_series_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install zebende==0.1.91

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zebende as zb
import time

### Set the number of time series to run the test

In [ ]:
series_count = 12

In [ ]:
url = 'https://tinyurl.com/zbtestdata64c'

In [ ]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 12)

In [ ]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
 4   Fc2.    19920 non-null  float64
 5   Fc4.    19920 non-null  float64
 6   Fc6.    19920 non-null  float64
 7   C5..    19920 non-null  float64
 8   C3..    19920 non-null  float64
 9   C1..    19920 non-null  float64
 10  Cz..    19920 non-null  float64
 11  C2..    19920 non-null  float64
dtypes: float64(12)
memory usage: 1.8 MB


In [ ]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 ... -1.4e-05 -2.9e-05 -1.5e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 ... -2.3e-05 -4.1e-05 -3.1e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 ... -3.6e-05 -5.3e-05 -4.1e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05 ...  2.5e-05  3.3e-05  3.7e-05]
 [ 3.8e-05  2.7e-05  2.8e-05 ...  4.0e-05  5.1e-05  5.5e-05]
 [ 5.0e-05  3.5e-05  4.1e-05 ...  3.8e-05  4.9e-05  5.5e-05]]


In [ ]:
start_time = time.time()
int_data = zb.integrated_series(mat)
dfa, dcca, pdcca = zb.p_dcca(mat, tws)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 213.0895299911499 seconds


In [ ]:
pdcca

array([[0.92012703, 0.82103312, 0.711603  , ..., 0.96425957, 0.895482  ,
        0.92978786],
       [0.92249668, 0.82453574, 0.71426117, ..., 0.96400389, 0.8934926 ,
        0.93071347],
       [0.9275426 , 0.83462291, 0.72682409, ..., 0.96543133, 0.89467528,
        0.93460199],
       ...,
       [0.95787447, 0.89553683, 0.81752623, ..., 0.97881613, 0.88832681,
        0.90523115],
       [0.95769706, 0.89550625, 0.81754472, ..., 0.97827412, 0.88682394,
        0.90264685],
       [0.95743313, 0.89529806, 0.81742775, ..., 0.97765777, 0.88540856,
        0.90017496]], shape=(42, 66))