In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from dcca import detrended_correlation
from itertools import combinations

import time

In [2]:
series_count = 4

In [3]:
url = 'https://tinyurl.com/zbtestdata64c'

In [4]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 4)

In [5]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
dtypes: float64(4)
memory usage: 622.6 KB


In [7]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 -1.2e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 -1.2e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 -1.9e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05  3.0e-06]
 [ 3.8e-05  2.7e-05  2.8e-05  1.9e-05]
 [ 5.0e-05  3.5e-05  4.1e-05  4.0e-05]]


In [8]:
start_time = time.time()
DCCA_of = np.array(list(combinations(range(mat.shape[1]), 2)), dtype=np.uintp)
P_DCCA_arr = np.full(shape=(tws.shape[0], DCCA_of.shape[0]) ,fill_value=np.nan, dtype=mat.dtype)
for n_index, n in enumerate(tws):
    for i in DCCA_of:
        x = mat[:,i[0]] # selecting series x
        y = mat[:,i[1]] # selecting series y
        P_DCCA_arr[n_index, i] = detrended_correlation(x=x, y=y, time_scale=n, time_lag=0) # Pdcca calculations
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 447.6767828464508 seconds


In [9]:
P_DCCA_arr

array([[0.711603  , 0.86202915, 0.94934976, 0.94934976,        nan,
               nan],
       [0.71426117, 0.86061591, 0.94893878, 0.94893878,        nan,
               nan],
       [0.72682409, 0.86457286, 0.95037339, 0.95037339,        nan,
               nan],
       [0.74153566, 0.87128318, 0.95264993, 0.95264993,        nan,
               nan],
       [0.75228129, 0.87656902, 0.95463692, 0.95463692,        nan,
               nan],
       [0.75910587, 0.88018155, 0.95624604, 0.95624604,        nan,
               nan],
       [0.7652045 , 0.88405868, 0.9581963 , 0.9581963 ,        nan,
               nan],
       [0.76939633, 0.88749448, 0.96017297, 0.96017297,        nan,
               nan],
       [0.77144186, 0.88919548, 0.96126435, 0.96126435,        nan,
               nan],
       [0.77468045, 0.89153095, 0.96270617, 0.96270617,        nan,
               nan],
       [0.77798498, 0.89375359, 0.96390296, 0.96390296,        nan,
               nan],
       [0.78159416, 0