<a href="https://colab.research.google.com/github/255ribeiro/paper_zebendelib/blob/main/notebooks/test_n_series_dcca_package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dcca import detrended_correlation
from itertools import combinations

import time

### Set The number of time series to run the test

In [ ]:
series_count = 12

In [ ]:
url = 'https://tinyurl.com/zbtestdata64c'

In [ ]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 12)

In [ ]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
 4   Fc2.    19920 non-null  float64
 5   Fc4.    19920 non-null  float64
 6   Fc6.    19920 non-null  float64
 7   C5..    19920 non-null  float64
 8   C3..    19920 non-null  float64
 9   C1..    19920 non-null  float64
 10  Cz..    19920 non-null  float64
 11  C2..    19920 non-null  float64
dtypes: float64(12)
memory usage: 1.8 MB


In [ ]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 ... -1.4e-05 -2.9e-05 -1.5e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 ... -2.3e-05 -4.1e-05 -3.1e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 ... -3.6e-05 -5.3e-05 -4.1e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05 ...  2.5e-05  3.3e-05  3.7e-05]
 [ 3.8e-05  2.7e-05  2.8e-05 ...  4.0e-05  5.1e-05  5.5e-05]
 [ 5.0e-05  3.5e-05  4.1e-05 ...  3.8e-05  4.9e-05  5.5e-05]]


In [ ]:
start_time = time.time()
DCCA_of = np.array(list(combinations(range(mat.shape[1]), 2)), dtype=np.uintp)
P_DCCA_arr = np.full(shape=(tws.shape[0], DCCA_of.shape[0]) ,fill_value=np.nan, dtype=mat.dtype)
for n_index, n in enumerate(tws):
    for i in DCCA_of:
        x = mat[:,i[0]] # selecting series x
        y = mat[:,i[1]] # selecting series y
        P_DCCA_arr[n_index, i] = detrended_correlation(x=x, y=y, time_scale=n, time_lag=0) # Pdcca calculations
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 4675.172034025192 seconds


In [ ]:
P_DCCA_arr

array([[0.58902651, 0.75154195, 0.82954453, ...,        nan,        nan,
               nan],
       [0.59792976, 0.75074282, 0.8302827 , ...,        nan,        nan,
               nan],
       [0.61854482, 0.75635227, 0.83468893, ...,        nan,        nan,
               nan],
       ...,
       [0.68329566, 0.78978574, 0.84298503, ...,        nan,        nan,
               nan],
       [0.68198159, 0.78840733, 0.84177379, ...,        nan,        nan,
               nan],
       [0.68071529, 0.78708255, 0.84056768, ...,        nan,        nan,
               nan]], shape=(42, 66))