In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import zebende as zb
import time

In [2]:
series_count = 4

In [3]:
url = 'https://tinyurl.com/zbtestdata64c'

In [4]:
df = pd.read_csv(url)
print(df.shape)
df = df.iloc[:, :series_count]
df.shape

(19920, 64)


(19920, 4)

In [5]:
tws =  np.array([4, 5, 7, 9, 11, 13, 16, 20, 23, 28, 33, 38, 45, 52, 60, 69, 79, 91, 104, 119, 135, 154, 174, 198, 223, 252, 285, 321,
  362, 407, 457, 513, 575, 645, 723, 809, 905, 1011, 1130, 1261, 1407, 1570])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19920 entries, 0 to 19919
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fc5.    19920 non-null  float64
 1   Fc3.    19920 non-null  float64
 2   Fc1.    19920 non-null  float64
 3   Fcz.    19920 non-null  float64
dtypes: float64(4)
memory usage: 622.6 KB


In [7]:
mat = df.to_numpy()
print(mat)

[[-5.7e-05 -1.3e-05 -1.5e-05 -1.2e-05]
 [-4.9e-05 -1.1e-05 -1.0e-05 -1.2e-05]
 [-5.5e-05 -1.7e-05 -1.6e-05 -1.9e-05]
 ...
 [ 2.3e-05  1.4e-05  1.1e-05  3.0e-06]
 [ 3.8e-05  2.7e-05  2.8e-05  1.9e-05]
 [ 5.0e-05  3.5e-05  4.1e-05  4.0e-05]]


In [8]:
start_time = time.time()
int_data = zb.integrated_series(mat)
dfa, dcca, pdcca = zb.p_dcca_pure_python(mat, tws)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 3076.2364416122437 seconds


In [9]:
pdcca

array([[0.92012703, 0.82103312, 0.711603  , 0.95543567, 0.86202915,
        0.94934976],
       [0.92249668, 0.82453574, 0.71426117, 0.95619693, 0.86061591,
        0.94893878],
       [0.9275426 , 0.83462291, 0.72682409, 0.95907942, 0.86457286,
        0.95037339],
       [0.93225023, 0.84502992, 0.74153566, 0.96200818, 0.87128318,
        0.95264993],
       [0.93575126, 0.85258676, 0.75228129, 0.96403165, 0.87656902,
        0.95463692],
       [0.93817892, 0.85739553, 0.75910587, 0.96527238, 0.88018155,
        0.95624604],
       [0.94052277, 0.861364  , 0.7652045 , 0.96633599, 0.88405868,
        0.9581963 ],
       [0.94231297, 0.86364934, 0.76939633, 0.96703014, 0.88749448,
        0.96017297],
       [0.94326969, 0.86469525, 0.77144186, 0.96733086, 0.88919548,
        0.96126435],
       [0.94467005, 0.86645842, 0.77468045, 0.96779128, 0.89153095,
        0.96270617],
       [0.94596916, 0.86835498, 0.77798498, 0.96829214, 0.89375359,
        0.96390296],
       [0.94720712, 0